const plansData = [
    {
      id: 1,
      task: "one",
      plan1: "I will study js course",
      plan2: "I will study react course",
      plan3: "I will study express course",
      report1: "I worked on js",
      report2: "I worked on react",
      report3: "I worked on express",
      time1: 3600,
      time2: 1800,
      time3: 5400,
      date: "12/23/2021",
      completed1: true,
      completed2: false,
      completed3: true
    },
    {
      id: 2,
      task: "two",
      plan1: "I will study js course",
      plan2: "I will study react course",
      plan3: "I will study express course",
      report1: "I worked on js",
      report2: "I worked on react",
      report3: "I worked on express",
      time1: 3600,
      time2: 3600,
      time3: 3600,
      date: "12/19/2021",
      completed1: false,
      completed2: true,
      completed3: false
    },
    {
      id: 3,
      task: "three",
      plan1: "I will study js course",
      plan2: "I will study react course",
      plan3: "I will study express course",
      report1: "I worked on js",
      report2: "I worked on react",
      report3: "I worked on express",
      time1: 3600,
      time2: 3600,
      time3: 3600,
      date: "12/02/2021",
      completed1: true,
      completed2: false,
      completed3: true
    },
    {
      id: 4,
      task: "four",
      plan1: "I will study js course",
      plan2: "I will study react course",
      plan3: "I will study express course",
      report1: "I worked on js",
      report2: "I worked on react",
      report3: "I worked on express",
      time1: 3600,
      time2: 3600,
      time3: 3600,
      date: "10/23/2021",
      completed1: true,
      completed2: false,
      completed3: true
    },
    {
      id: 5,
      task: "five",
      plan1: "I will study js course",
      plan2: "I will study react course",
      plan3: "I will study express course",
      report1: "I worked on js",
      report2: "I worked on react",
      report3: "I worked on express",
      time1: 3600,
      time2: 3600,
      time3: 3600,
      date: "11/23/2021",
      completed1: true,
      completed2: false,
      completed3: true
    }
  ];
  
  export default plansData;
  